language: node_js

node_js:
  - 'node'

sudo: false

env:
  global:
    secure: "M/T6lU34blq2CQpXsOFhiqA3EfrG6dV/lC3Ib3sYJLVFM1i/jD4vxobb5vZT2pKmTsjiL7czr4jTX4NeeQFBMTgyKFapgOOXnsGBzLWa2pq3dCxdTRkXlMZrFMxlca7TR2Xm/qXtToLy0yBQMU+V/IqEfBsFQkuk3XqXNLs07VjYD/BooyCCej462X7xkr3L6flmPCgesHgoXWXiV4QLsZd51WRTzTWopQ8zJcORZkeoV7Sy495h4a2cdkKzFgNMezHR5avKIB6E3/y37PQReU3nQ0Qh90h3nq8E7DQg4fLLRI41B5lGOv39MG/129QzwqMAsSIH6hwPlAhlCUvWT1TQkwwxtPQgUriDYm70EANzSkqvLweFvItqROgcfLFE8BtdDpwP/LLz0rn7RlW24JSsFOZAp09J+d40jnVYRoxPDSrbbT04DwawkyOEpeigkcvvETWp5nHAuqUq0aa6vmYxc9h7i62PrPMEZc46ZK6lG6RULbwoM0vq8uyTzjPY23qEO8yVfeoGbS1GC/pJ0hzSSMe9fSpobYw+SOkpro16B8xGa5zqbx2QMNWbQMtRXqF/KRolJoqqbmzGbgBhx0vjnrO5dJEC/wEgR23ifdf0uaivC4i6o699/O4X2aHBTS9z5/1RxM6WzaEONVGuZYj8gb13pmAGlWKL/2ho5Z4="

codecov: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm install -g codecov

install:
  - yarn

cache:
  yarn: true
  directories:
    - node_modules

stages:
  - test
  - coverage
  - build

deploy:
  skip_cleanup: true
  provider: script
  script: yarn run deploy
  on:
    tags: true

jobs:
  include:
    - stage: test
      script:
        - yarn run lint
        - yarn run test
      on:
        branch: master

    - stage: coverage
      if: branch = master
      script:
        - yarn run test:co
        - codecov
    
    - stage: build
      script: yarn run build

matrix:
  fast_finish: true

git:
  depth: 1