language: node_js

node_js:
  - 'node'

sudo: false

codecov: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm install -g codecov

install:
  - yarn

cache:
  yarn: true
  directories:
    - node_modules

stages:
  - test
  - coverage

env:
  global:
    - secure: "d2thNEg8n57peBKP6Gd1l88LsUth9PZ2323WuXsSlo46m3BNgPk2Z3/PWGhEcxjxilnta7VwiE+gxAUwh9F2nMzh631w8P6i7iQln7If5zg40+VUlWe3dLly9fH/oCdwrh5t8qhsFgVDMUZMQEhjPmLF/pnJ1hc7elWdJgzMTN8USfLgSJp87QExQIFq7nAxgMvuRJY8lHV1yM/mR/XhVFEY+gXulMZ1jIi+/7oy5tO0EM7RUER9lLmkQXQquxHcrwc34EBVGhPw/tz2qyfiAPXoH02/F2jOkDquIptpCZOU93N2e3yVpaCkdhI0Kl542uUfHgbE+T+ANvKJLdn6I/cgluZGqohc3sBgQSBsMFR4WGbc2tdTdm6K5v/f+9vY/aSaRY1ApZBCAXNkRoegnuLECKUuYodp+niuDmG7pyUtJaM/j8zsBRI6kGMnFsUdjTPpwTN3fJmhdy1xkpm9VbHK6OaDWnHHmlHdniartG/KnHlJxbjvUSmGCN5sXlkf4v+jh9mkJ+mohlYmfteiPcxD6EPE540ZL1YXNUrvJd+JKdSmcGhjM3naRyBlCdliRYcZ8VWhvG9EwUSEDNDwOYXoZCttzeUg6aQfLyFSM47BII84BwiXO7p9h5Ml6/v6VEaWU5biE6HX/k3DjtIJ8ODrMM5MZvfhHo+tbLBHJVw="

deploy:
  skip_cleanup: true
  provider: script
  script: yarn run deploy
  on:
    tags: true

jobs:
  include:
    - stage: test
      script:
        - yarn run lint
        - yarn run test
      on:
        branch: master

    - stage: coverage
      if: branch = master
      script:
        - yarn run test:co
        - codecov

matrix:
  fast_finish: true

git:
  depth: 1