language: node_js

node_js:
  - 'node'

sudo: false

env:
  global:
    secure: "MB97rm8ALw56Zu3zWnLBKZ5oAFzsy6n3vcfer2GdizEYoDyAjOyrpOUSbjMVO+D3jW7NTgVYI1QBAZxrARjCCIrIFYWms1UDiIhDqtuvmmzdonRwDXw1Xm0sM+ydnfk56bscgGqw+xuD+1Mk9BT5gNFiWevt3uXAWnA0YK8uZyxsTSHx/vzdzp9qGnaOMIrdum3fPG5yLTHUzDT+1vd10/N6B3RzDcLFQkpa7lKXydB0tmT6su17yGz1mWlz32WR8z2jF1XAw/6rlvjnbcR0J3pzWzsj4YOtbpfh9s2PocoYPdiOH/GaX7zT+IUIGHFAqKDsnR9AjIiJoKPCATeMfY2NH8ewuVsabP7l88TdLuAkCnV+jspRBo+2tw4bbeaFJwpHV9hIfgAETLjyrIXPrb7kS11TCvD//TzHJIGzGTUBsP4BV3fozTotpt2t49mh6VHgUaN51hvdY2xpKMcaKoXSL1L7dS9rWaavnasI2ysNliuzFylcGsr3y1+9r2aP2Rm/UefNmCCWC/NHtzU7toXr+jrHSfl7zzlrSAjulyuoGpVJ2jyBDIMwP/WiC1DosReeKX3QjWaXmzdlFJTD5svWDTkBPDuB9orBNeK5y1n8L09chZWZeNtEc49lw/pjnZLRpy6NL0hDfmwlKpENg+GdreCkG1VNlqBIn1WuLp4="

codecov: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm install -g codecov

install:
  - yarn

cache:
  yarn: true
  directories:
    - node_modules

stages:
  - test
  - coverage

deploy:
  skip_cleanup: true
  provider: script
  script: yarn run deploy
  on:
    tags: true

jobs:
  include:
    - stage: test
      script:
        - yarn run lint
        - yarn run test
      on:
        branch: master

    - stage: coverage
      if: branch = master
      script:
        - yarn run test:co
        - codecov

matrix:
  fast_finish: true

git:
  depth: 1